# Generated by Django 5.0.3 on 2024-05-17 09:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.CharField(default='default_id', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{3}$', 'Track_id must be exactly 3 digits')])),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='default_username', max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Track_id must be exactly 4 digits')])),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('blood_state', models.CharField(blank=True, max_length=10, null=True)),
                ('health_state', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain at least one digit and one character, and be at least 8 characters long.', regex='^(?=.*[0-9])(?=.*[a-zA-Z]).{8,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=55)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain exactly 10 digits.', regex='^[0-9]{10}$')])),
                ('cvc', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.CharField(default='default_id', max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Track_id must be exactly 4 digits')])),
                ('friend_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('location', models.CharField(max_length=255)),
                ('code', models.CharField(choices=[('Red', '221'), ('Green', '222'), ('Orange', '223')], max_length=255, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency', to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('specialization', models.CharField(blank=True, max_length=25, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='MyApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='MyApp.user')),
            ],
        ),
    ]
